version: "3"

services:
  db:
    build:
      context: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    networks:
      - desafio
    tty: true
    image: ceduardogodoi/desafio-node-mysql

  app:
    build:
      context: app
    container_name: app
    networks:
      - desafio
    tty: true
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    depends_on:
      - db
    command: npm start
    image: ceduardogodoi/desafio-node-app

  nginx:
    build:
      context: nginx
    container_name: nginx
    ports:
      - "8080:8080"
    networks:
      - desafio
    tty: true
    depends_on:
      - app
    image: ceduardogodoi/desafio-node-nginx

networks:
  desafio:
    driver: bridge
